# Generated by rust2rpm 28
%bcond check 1

%global crate listenbrainz-mpd

Name:           rust-listenbrainz-mpd
Version:        2.3.9
Release:        %autorelease
Summary:        ListenBrainz submission client for MPD

License:        AGPL-3.0-only
URL:            https://crates.io/crates/listenbrainz-mpd
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
ListenBrainz submission client for MPD.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE.txt
%license LICENSE.dependencies
%doc CHANGELOG.md
%doc README.md
%{_bindir}/listenbrainz-mpd

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
